[package]
name = "axum-project"
version = "0.1.0"
edition = "2021"

[lib]
name="pkg"
path = "./src/lib.rs"

[dependencies]
axum = "0.7.7"
serde_json = "1.0.132"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
